#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# java applications
wmname LG3D
export _JAVA_AWT_WM_NONREPARENTING=1

xsetroot -cursor_name left_ptr &

# polybar
$HOME/.config/polybar/launch.sh

# fcitx5
fcitx5 &

# vmware copy/paste
vmware-user &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   false
bspc config gapless_monocle      false
